version: "2"
linters:
  enable:
    - copyloopvar
    - dupword
    - gosec
    - misspell
    - nolintlint
    - revive
    - unconvert
  disable:
    - errcheck
  settings:
    gosec:
      excludes:
        - G204
        - G305
        - G306
        - G402
        - G404
        - G115
    nolintlint:
      allow-unused: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
